services:
  decidim-staging:
    image: ghcr.io/gasparbucuane/decidim:${GIT_STAGING_REF:-staging}
    container_name: decidim_staging
    volumes:
      - staging-storage:/app/storage
    restart: ${RESTART_POLICY:-unless-stopped}
    env_file:
      - .env
      - .env.staging
    labels:
      - traefik.enable=true
      - traefik.http.routers.decidim.rule=Host(`${DECIDIM_STAGING_HOST}`)
      - traefik.http.routers.decidim.entrypoints=websecure
      - traefik.http.routers.decidim.tls=true
      - traefik.http.routers.decidim.tls.certresolver=le
      - traefik.http.services.decidim.loadbalancer.server.port=3000
    networks:
      - web
      - backend

volumes:
  staging-storage:

networks:
  web:
    external: true
  backend:
    external: true

