services:
  decidim-dev:
    image: ghcr.io/gasparbucuane/decidim:${GIT_DEV_REF:-dev}
    container_name: decidim_dev
    volumes:
      - dev-storage:/app/storage
    restart: ${RESTART_POLICY:-unless-stopped}
    env_file:
      - .env
      - .env.dev
    labels:
      - traefik.enable=true
      - traefik.http.routers.decidim.rule=Host(`${DECIDIM_DEV_HOST}`)
      - traefik.http.routers.decidim.entrypoints=websecure
      - traefik.http.routers.decidim.tls=true
      - traefik.http.routers.decidim.tls.certresolver=le
      - traefik.http.services.decidim.loadbalancer.server.port=3000
    networks:
      - web
      - backend

volumes:
  dev-storage:

networks:
  web:
    external: true
  backend:
    external: true

